package net.kunmc.lab.commandlib.util.nms;

import java.util.List;

/**
 * The typed NMS modules bundled into the spigot jar (see {@code docs/agents/nms-build.md}). Generated by
 * {@code tools/nms-codegen/generate.py} from its module table; edit the table and regenerate instead of this file.
 */
final class TypedNmsModules {
    static final List<NMSClassRegistry.TypedModule> MODULES = List.of(
            new NMSClassRegistry.TypedModule("spigot_1_16_5", "1.16.4", "1.16.5"),
            new NMSClassRegistry.TypedModule("spigot_1_17_1", "1.17.1", "1.17.1"),
            new NMSClassRegistry.TypedModule("spigot_1_18", "1.18", "1.18"),
            new NMSClassRegistry.TypedModule("spigot_1_18_1", "1.18.1", "1.18.1"),
            new NMSClassRegistry.TypedModule("spigot_1_18_2", "1.18.2", "1.18.2"),
            new NMSClassRegistry.TypedModule("spigot_1_19", "1.19", "1.19"),
            new NMSClassRegistry.TypedModule("spigot_1_19_1", "1.19.1", "1.19.1"),
            new NMSClassRegistry.TypedModule("spigot_1_19_2", "1.19.2", "1.19.2"),
            new NMSClassRegistry.TypedModule("spigot_1_19_3", "1.19.3", "1.19.3"),
            new NMSClassRegistry.TypedModule("spigot_1_19_4", "1.19.4", "1.19.4"),
            new NMSClassRegistry.TypedModule("spigot_1_20_1", "1.20", "1.20.1"),
            new NMSClassRegistry.TypedModule("spigot_1_20_2", "1.20.2", "1.20.2"),
            new NMSClassRegistry.TypedModule("spigot_1_20_4", "1.20.4", "1.20.4"),
            new NMSClassRegistry.TypedModule("spigot_1_20_6", "1.20.6", "1.20.6"),
            new NMSClassRegistry.TypedModule("spigot_1_21_1", "1.21", "1.21.1"),
            new NMSClassRegistry.TypedModule("paper_1_20_6", "1.20.5", "1.20.6")
                    .withWrapperVersions("NMSDataPackResources", "1.20.6", "1.20.6"),
            new NMSClassRegistry.TypedModule("paper_1_20_6_spigot", "paper_1_20_6", "1.20.5", "1.20.6")
                    .withWrapperVersions("NMSDataPackResources", "1.20.6", "1.20.6"));

    private TypedNmsModules() {
    }
}
